package fr.sparadrap.ecf.view.swingview.customer;

import fr.sparadrap.ecf.database.dao.CustomerDAO;
import fr.sparadrap.ecf.model.lists.person.CustomersList;
import fr.sparadrap.ecf.model.person.Customer;
import fr.sparadrap.ecf.view.swingview.DisplayList;
import fr.sparadrap.ecf.view.swingview.tablemodele.TableModele;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.List;

import static fr.sparadrap.ecf.view.swingview.DisplayList.*;

public class CustomersPanel extends JPanel {
    private JPanel customersPanel;
    private JButton addButton;
    private JButton editButton;
    private JButton deleteButton;
    private JPanel bottomBar;
    private JPanel topPanel;
    private JLabel titleLabel;
    private JPanel centerPanel;
    private JTextField searchField;
    private JButton searchButton;
    private JButton showDetailsBtn;
    private JPanel tableContainer;
    private JPanel titlePanel;
    private JPanel searchPanel;
    private JTable customersTable;
    private JScrollPane scrollPane;
    private JPanel tablePanel;
    private JPanel left;
    private JPanel right;
    private JTable customerTable;
    private DisplayList customerDisplayList;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        customersPanel = new JPanel();
        customersPanel.setLayout(new BorderLayout(0, 0));
        customersPanel.setBackground(new Color(-1769250));
        customersPanel.setForeground(new Color(-1762260));
        bottomBar = new JPanel();
        bottomBar.setLayout(new GridBagLayout());
        customersPanel.add(bottomBar, BorderLayout.SOUTH);
        right = new JPanel();
        right.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        bottomBar.add(right, gbc);
        addButton = new JButton();
        addButton.setBackground(new Color(-12020664));
        addButton.setForeground(new Color(-328193));
        addButton.setText("ajout client");
        addButton.setToolTipText("Nouveau client");
        right.add(addButton);
        left = new JPanel();
        left.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        bottomBar.add(left, gbc);
        showDetailsBtn = new JButton();
        showDetailsBtn.setEnabled(false);
        showDetailsBtn.setText("Afficher");
        left.add(showDetailsBtn);
        editButton = new JButton();
        editButton.setBackground(new Color(-13690907));
        editButton.setEnabled(false);
        editButton.setForeground(new Color(-2171675));
        editButton.setText("Modifier");
        left.add(editButton);
        deleteButton = new JButton();
        deleteButton.setBackground(new Color(-1768689));
        deleteButton.setEnabled(false);
        deleteButton.setForeground(new Color(-1025));
        deleteButton.setText("Supprimer");
        left.add(deleteButton);
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        left.add(topPanel);
        topPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        titlePanel = new JPanel();
        titlePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        topPanel.add(titlePanel, gbc);
        titleLabel = new JLabel();
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setText("Gestion des Clients");
        titlePanel.add(titleLabel);
        centerPanel = new JPanel();
        centerPanel.setLayout(new BorderLayout(0, 0));
        centerPanel.setBackground(new Color(-1716992));
        customersPanel.add(centerPanel, BorderLayout.CENTER);
        searchPanel = new JPanel();
        searchPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        centerPanel.add(searchPanel, BorderLayout.NORTH);
        searchPanel.setBorder(BorderFactory.createTitledBorder(null, "Recherche", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        searchField = new JTextField();
        searchField.setColumns(20);
        searchField.setMinimumSize(new Dimension(50, 25));
        searchField.setPreferredSize(new Dimension(226, 25));
        searchField.setText("");
        searchField.setToolTipText("votre recherche");
        searchPanel.add(searchField);
        searchButton = new JButton();
        searchButton.setText("Search");
        searchButton.setToolTipText("Rechercher");
        searchPanel.add(searchButton);
        tablePanel = new JPanel();
        tablePanel.setLayout(new BorderLayout(0, 0));
        tablePanel.setPreferredSize(new Dimension(400, 300));
        centerPanel.add(tablePanel, BorderLayout.CENTER);
        scrollPane = new JScrollPane();
        tablePanel.add(scrollPane, BorderLayout.CENTER);
        customersTable = new JTable();
        scrollPane.setViewportView(customersTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return customersPanel;
    }

    public enum FormModes {
        ADD,
        EDIT
    }

    public CustomersPanel() {

        this.setLayout(new GridLayout(1, 1));

        // Vérifier que customersPanel est initialisé
        if (customersPanel == null) {
            customersPanel = new JPanel(new BorderLayout());
            System.out.println("customersPanel null");
        }

        this.add(customersPanel);

        // Vérifier que tablePanel existe avant d'ajouter le DisplayList
        if (tablePanel == null) {
            tablePanel = new JPanel(new BorderLayout());
            // Ajouter tablePanel au customersPanel si nécessaire
            if (centerPanel != null) {
                centerPanel.add(tablePanel, BorderLayout.CENTER);
            }
        }


        try {
            customerDisplayList = new DisplayList(0);
            CustomerDAO customerDAO = new CustomerDAO();
            for (Customer c : customerDAO.findAll()) {
                System.out.println(c.getFullName());
            }
        } catch (Exception e) {
            System.out.println("Erreur occured" + e.getMessage());
        }

        System.out.println();
        tablePanel.add(customerDisplayList, BorderLayout.CENTER);


        customerDisplayList.getTable().getSelectionModel().addListSelectionListener(e -> {
            boolean selected = customerDisplayList.getTable().getSelectedRow() != -1;
            showDetailsBtn.setEnabled(selected);
            editButton.setEnabled(selected);
            deleteButton.setEnabled(selected);
        });

        showDetailsBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showCustomersDetails();

            }
        });

        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editCustomer();
            }
        });

        deleteButton.addActionListener(e -> {
            deleteCustomer();
        });


        searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                searchCustomers();
            }
        });


        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addCustomer();
            }
        });
    }

    /**
     * recherche des patients dans le tableau  et affiche un nouveau tableau filtré
     */
    private void searchCustomers() {
        String search = searchField.getText().trim();
        try {
            CustomerDAO customerDAO = new CustomerDAO();
            List<Customer> filteredList = customerDAO.search(search);
            customerDisplayList.configTable(filteredList, HEADER_CUSTOMERS, USER_COLUMN_CLASSES);
        } catch (Exception e) {
            System.err.println("Erreur searchCustomers" + e.getMessage());
        }

    }


    /**
     * Met a jour la visibilité des boutons
     */
    private void updateButtonsState() {
        // boolean hasCustomers = !CustomersList.getCustomers().isEmpty();
        boolean hasSelection = customersTable.getSelectedRow() != -1;
        showDetailsBtn.setEnabled(hasSelection);
        deleteButton.setEnabled(hasSelection);
        editButton.setEnabled(hasSelection);
        searchButton.setEnabled(true);
        addButton.setEnabled(true);
    }

    /**
     * affiche le detail du client séléctionné
     */
    private void showCustomersDetails() {
        Customer selectedCustomer = getSelectedCustomer();
        if (selectedCustomer == null) {
            JOptionPane.showMessageDialog(this, "Selectionner d'abord un client", "Aucun client selectionné", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(customersPanel, selectedCustomer.showDetails(), "Détails du CLient", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * selectionne un client
     *
     * @return le client
     */
    private Customer getSelectedCustomer() {
        return getSelectedItem(customerDisplayList.getTable(), (TableModele<Customer>) customerDisplayList.getTable().getModel());

    }


    /**
     * affiche la fenetre d'ajout d'un nouveau patient
     */
    private void addCustomer() {
        CustomerFormPanel formPanel = new CustomerFormPanel(new Customer(), FormModes.ADD);
        formPanel.setVisible(true);
        formPanel.pack();
    }


    /**
     * affiche la fenetre d'edition d'un patient existant
     */
    private void editCustomer() {
        Customer selectedCustomer = getSelectedCustomer();
        if (selectedCustomer == null) {
            JOptionPane.showMessageDialog(this, "Selectionner d'abord un client", "Aucun client selectionné", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CustomerFormPanel formPanel = new CustomerFormPanel(selectedCustomer, FormModes.EDIT);
        formPanel.setVisible(true);
        formPanel.pack();
    }

    /**
     * supprime le patient selectionné
     */
    private void deleteCustomer() {
        try {

            Customer selectedCustomer = getSelectedCustomer();
            if (selectedCustomer == null) {
                JOptionPane.showMessageDialog(this, "Selectionner d'abord un client", "Aucun client selectionné", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Voulez-vous vraiment supprimer le client \"" + selectedCustomer.getFullName() + "\" ?",
                    "Confirmation de suppression",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    CustomerDAO customerDAO = new CustomerDAO();
                    customerDAO.deleteById(selectedCustomer.getId());
                    refreshTable();
                    updateButtonsState();
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur occured" + e.getMessage());
        }


    }

    /**
     * Remise a zero du tableau
     */
    private void refreshTable() {
        customerDisplayList.configTable(CustomersList.getCustomers(), HEADER_CUSTOMERS, USER_COLUMN_CLASSES);
    }
}


