package fr.sparadrap.ecf.view.swingview;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import fr.sparadrap.ecf.database.dao.CustomerDAO;
import fr.sparadrap.ecf.database.dao.DoctorDAO;
import fr.sparadrap.ecf.model.person.Customer;
import fr.sparadrap.ecf.model.person.Doctor;


import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;

public class HomePanel extends JPanel {
    private JPanel homePanel;
    private JPanel topPanel;
    private JLabel homeTitleLabel;
    private JPanel centerPanel;
    private JPanel bottomPanel;
    private JPanel detailsClientContainer;
    private JPanel filterPanel;
    private JComboBox customerComboBox;
    private JPanel displayDetailPanel;
    private JComboBox doctorCombobox;
    private JLabel customerDetailLabel;
    private JTextPane customerPane;
    private JPanel detailsDoctorContainer;
    private JPanel StatPanel;
    private JTextPane doctorPane;

    public HomePanel() {
        if (homePanel == null) {
            homePanel = new JPanel();
        }
        this.add(homePanel);
        try (CustomerDAO customerDAO = new CustomerDAO()) {
            customerDAO.findAll().forEach(customer -> {
                customerComboBox.addItem(customer);
            });

        } catch (SQLException | IOException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }

        try (DoctorDAO doctorDAO = new DoctorDAO()) {
            doctorDAO.findAll().forEach(doctor -> {
                System.out.println(doctor.getFullName());
                doctorCombobox.addItem(doctor);
            });
        } catch (Exception e) {
            throw new RuntimeException(e);
        }


        customerComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Customer customer = (Customer) customerComboBox.getSelectedItem();
                if (customer != null) {
                    customerPane.setText(customer.showDetails());
                }

            }
        });


        doctorCombobox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Doctor selectedDoctor = (Doctor) doctorCombobox.getSelectedItem();
                if (selectedDoctor != null) {
                    doctorPane.setText(selectedDoctor.showDetails());
                    System.out.println("ID du docteur sélectionné : " + selectedDoctor.getId());
                }

            }
        });
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        homePanel = new JPanel();
        homePanel.setLayout(new BorderLayout(0, 0));
        homePanel.setPreferredSize(new Dimension(1000, 700));
        topPanel = new JPanel();
        topPanel.setLayout(new BorderLayout(0, 0));
        homePanel.add(topPanel, BorderLayout.NORTH);
        homeTitleLabel = new JLabel();
        homeTitleLabel.setHorizontalAlignment(0);
        homeTitleLabel.setText("Bienvenue sur sparadrap");
        topPanel.add(homeTitleLabel, BorderLayout.CENTER);
        centerPanel = new JPanel();
        centerPanel.setLayout(new GridBagLayout());
        homePanel.add(centerPanel, BorderLayout.CENTER);
        detailsClientContainer = new JPanel();
        detailsClientContainer.setLayout(new BorderLayout(0, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        centerPanel.add(detailsClientContainer, gbc);
        detailsClientContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Afficher les details cllent", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        filterPanel = new JPanel();
        filterPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        detailsClientContainer.add(filterPanel, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        filterPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        customerComboBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Selectionner un patient");
        customerComboBox.setModel(defaultComboBoxModel1);
        panel1.add(customerComboBox);
        displayDetailPanel = new JPanel();
        displayDetailPanel.setLayout(new BorderLayout(0, 0));
        detailsClientContainer.add(displayDetailPanel, BorderLayout.CENTER);
        displayDetailPanel.setBorder(BorderFactory.createTitledBorder(null, "", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        customerPane = new JTextPane();
        customerPane.setText("Selectionner un client pour afficher le detail");
        displayDetailPanel.add(customerPane, BorderLayout.CENTER);
        StatPanel = new JPanel();
        StatPanel.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        centerPanel.add(StatPanel, gbc);
        StatPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Statistiques", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        detailsDoctorContainer = new JPanel();
        detailsDoctorContainer.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        centerPanel.add(detailsDoctorContainer, gbc);
        detailsDoctorContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Afficher les details medecin", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        detailsDoctorContainer.add(panel2, BorderLayout.NORTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        doctorCombobox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel2 = new DefaultComboBoxModel();
        defaultComboBoxModel2.addElement("Selectionner un medecin");
        doctorCombobox.setModel(defaultComboBoxModel2);
        panel3.add(doctorCombobox);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        detailsDoctorContainer.add(panel4, BorderLayout.CENTER);
        doctorPane = new JTextPane();
        doctorPane.setText("Selectionner un médecin pour afficher le detail");
        panel4.add(doctorPane, BorderLayout.NORTH);
        bottomPanel = new JPanel();
        bottomPanel.setLayout(new BorderLayout(0, 0));
        homePanel.add(bottomPanel, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return homePanel;
    }

}
