package fr.sparadrap.ecf.view.swingview.doctor;

import fr.sparadrap.ecf.model.lists.person.CustomersList;
import fr.sparadrap.ecf.model.lists.person.DoctorList;
import fr.sparadrap.ecf.model.person.Customer;
import fr.sparadrap.ecf.model.person.Doctor;
import fr.sparadrap.ecf.view.swingview.DisplayList;
import fr.sparadrap.ecf.view.swingview.tablemodele.TableModele;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import static fr.sparadrap.ecf.view.swingview.DisplayList.*;

public class DoctorsPanel extends JPanel {
    private JPanel doctorsPanel;
    private JButton addButton;
    private JButton editButton;
    private JButton deleteButton;
    private JPanel bottomBar;
    private JPanel topPanel;
    private JLabel titleLabel;
    private JPanel centerPanel;
    private JTextField searchField;
    private JButton searchButton;
    private JButton showDetailsBtn;
    private JPanel tableContainer;
    private JPanel titlePanel;
    private JPanel searchPanel;
    private JTable doctorsTable;
    private JScrollPane scrollPane;
    private JPanel tablePanel;
    private JPanel left;
    private JPanel right;
    private JButton showCustomersBtn;
    private JButton showDoctorPrescriptionsBtn;
    private DisplayList doctorsDisplayList;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        doctorsPanel = new JPanel();
        doctorsPanel.setLayout(new BorderLayout(0, 0));
        doctorsPanel.setBackground(new Color(-1769250));
        doctorsPanel.setForeground(new Color(-1762260));
        bottomBar = new JPanel();
        bottomBar.setLayout(new GridBagLayout());
        doctorsPanel.add(bottomBar, BorderLayout.SOUTH);
        right = new JPanel();
        right.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        bottomBar.add(right, gbc);
        addButton = new JButton();
        addButton.setBackground(new Color(-12020664));
        addButton.setForeground(new Color(-328193));
        addButton.setText("ajout medecin");
        addButton.setToolTipText("Nouveau client");
        right.add(addButton);
        left = new JPanel();
        left.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        bottomBar.add(left, gbc);
        showDetailsBtn = new JButton();
        showDetailsBtn.setEnabled(false);
        showDetailsBtn.setText("Afficher");
        left.add(showDetailsBtn);
        editButton = new JButton();
        editButton.setBackground(new Color(-13690907));
        editButton.setEnabled(false);
        editButton.setForeground(new Color(-2171675));
        editButton.setText("Modifier");
        left.add(editButton);
        deleteButton = new JButton();
        deleteButton.setBackground(new Color(-1768689));
        deleteButton.setEnabled(false);
        deleteButton.setForeground(new Color(-1025));
        deleteButton.setText("Supprimer");
        left.add(deleteButton);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        bottomBar.add(panel1, gbc);
        showCustomersBtn = new JButton();
        showCustomersBtn.setEnabled(false);
        showCustomersBtn.setText("Patients");
        panel1.add(showCustomersBtn);
        showDoctorPrescriptionsBtn = new JButton();
        showDoctorPrescriptionsBtn.setEnabled(false);
        showDoctorPrescriptionsBtn.setText("Ordonnances");
        panel1.add(showDoctorPrescriptionsBtn);
        topPanel = new JPanel();
        topPanel.setLayout(new GridBagLayout());
        doctorsPanel.add(topPanel, BorderLayout.NORTH);
        topPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        titlePanel = new JPanel();
        titlePanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        topPanel.add(titlePanel, gbc);
        titleLabel = new JLabel();
        titleLabel.setHorizontalAlignment(0);
        titleLabel.setText("Gestion des Medecins");
        titlePanel.add(titleLabel);
        centerPanel = new JPanel();
        centerPanel.setLayout(new BorderLayout(0, 0));
        centerPanel.setBackground(new Color(-1716992));
        doctorsPanel.add(centerPanel, BorderLayout.CENTER);
        searchPanel = new JPanel();
        searchPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        centerPanel.add(searchPanel, BorderLayout.NORTH);
        searchPanel.setBorder(BorderFactory.createTitledBorder(null, "Recherche", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        searchField = new JTextField();
        searchField.setColumns(20);
        searchField.setMinimumSize(new Dimension(50, 25));
        searchField.setPreferredSize(new Dimension(226, 25));
        searchField.setToolTipText("votre recherche");
        searchPanel.add(searchField);
        searchButton = new JButton();
        searchButton.setIcon(new ImageIcon(getClass().getResource("/fr/sparadrap/ecf/view/swingview/ressources/recherche.png")));
        searchButton.setText("");
        searchButton.setToolTipText("Rechercher");
        searchPanel.add(searchButton);
        tablePanel = new JPanel();
        tablePanel.setLayout(new BorderLayout(0, 0));
        tablePanel.setPreferredSize(new Dimension(400, 300));
        centerPanel.add(tablePanel, BorderLayout.CENTER);
        scrollPane = new JScrollPane();
        tablePanel.add(scrollPane, BorderLayout.CENTER);
        doctorsTable = new JTable();
        scrollPane.setViewportView(doctorsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return doctorsPanel;
    }

    public enum FormModes {
        ADD,
        EDIT
    }

    public DoctorsPanel() {
        this.setLayout(new GridLayout(1, 1));
        this.add(doctorsPanel);
        try {
            doctorsDisplayList = new DisplayList(1);
        } catch (Exception e) {
            e.printStackTrace();
        }

        tablePanel.add(doctorsDisplayList);
        updateButtonsState();


        doctorsDisplayList.getTable().getSelectionModel().addListSelectionListener(e -> {
            updateButtonsState();
        });

        // Boutons d'action

        searchField.addActionListener(e -> searchDoctors());
        showDetailsBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDoctorDetails();

            }
        });

        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editDoctor();
            }
        });

        deleteButton.addActionListener(e -> {
            deleteDoctor();
        });


        searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                searchDoctors();
            }
        });


        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                addDoctor();
            }
        });
        showCustomersBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDoctorCustomers();

            }
        });
        showDoctorPrescriptionsBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDoctorPrescriptions();
            }
        });
    }


    private void searchDoctors() {
        String search = searchField.getText().trim();
        if (search.isEmpty()) {
            refreshTable();
            return;
        }
        List<Doctor> filteredList = DoctorList.filterDoctor(search);
        doctorsDisplayList.configTable(filteredList, HEADER_DOCTORS, USER_COLUMN_CLASSES);
    }


    private void updateButtonsState() {
        boolean hasDoctors = !DoctorList.getDoctors().isEmpty();
        boolean hasSelection = doctorsDisplayList.getTable().getSelectedRow() != -1;
        showDetailsBtn.setEnabled(hasSelection);
        deleteButton.setEnabled(hasSelection);
        editButton.setEnabled(hasSelection);
        showCustomersBtn.setEnabled(hasSelection);
        showDoctorPrescriptionsBtn.setEnabled(hasSelection);
        searchButton.setEnabled(true);
        addButton.setEnabled(true);
    }

    /**
     * affiche la fenetre de details du medecin selectionné
     */
    private void showDoctorDetails() {
        Doctor selectedDoctor = getSelectedDoctor();

        if (selectedDoctor == null) {
            JOptionPane.showMessageDialog(this, "Selectionner d'abord un médecin", "Aucun client selectionné", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(doctorsPanel, selectedDoctor.showDetails(), "Détails du Médecin", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * selectionne un medecin dans le tableau
     *
     * @return un Medecin
     */
    private Doctor getSelectedDoctor() {
        return getSelectedItem(doctorsDisplayList.getTable(), (TableModele<Doctor>) doctorsDisplayList.getTable().getModel());

    }


    /**
     * Filtre les patients associé a un médecin en particulier
     *
     * @param doctor
     * @return Liste de patients
     */
    private List<Customer> getCustomersByDoctor(Doctor doctor) {
        List<Customer> customers = CustomersList.getCustomers().stream()
                .filter(customer -> customer.getDoctor() != null && customer.getDoctor().equals(doctor))
                .toList();
        return customers;
    }


    /**
     * affiche la fenetre d'ajout de medecin
     */
    private void addDoctor() {
        DoctorFormPanel formPanel = new DoctorFormPanel(null, FormModes.ADD);
        formPanel.setVisible(true);
    }

    /**
     * affiche la fenetre  qui montre la liste des patients du médecin selectionné
     */
    public void showDoctorCustomers() {
        Doctor selectedDoctor = getSelectedDoctor();
        if (selectedDoctor != null) {
            DoctorCustomersDialog dialog = new DoctorCustomersDialog(selectedDoctor);
            dialog.setVisible(true);
        }
    }

    /**
     * affiche la fenetre montrant les ordonnances d'un médecin
     */
    private void showDoctorPrescriptions() {
        Doctor selectedDoctor = getSelectedDoctor();
        if (selectedDoctor != null) {
            DoctorPrescriptionsDialog dialog = new DoctorPrescriptionsDialog(selectedDoctor);
            dialog.setVisible(true);
        }
    }


    private void editDoctor() {
        Doctor selectedDoctors = getSelectedDoctor();
        if (selectedDoctors == null) {
            JOptionPane.showMessageDialog(this, "Selectionner d'abord un Medecin", "Aucun médecin selectionné", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DoctorFormPanel formPanel = new DoctorFormPanel(selectedDoctors, FormModes.EDIT);
        formPanel.setVisible(true);
    }

    private void deleteDoctor() {
        Doctor selectedDoctor = getSelectedDoctor();
        if (selectedDoctor == null) {
            JOptionPane.showMessageDialog(this, "Selectionner d'abord un médecin", "Aucun médecin selectionné", JOptionPane.ERROR_MESSAGE);
            return;
        }
        List<Customer> customers = getCustomersByDoctor(selectedDoctor);
        if (!customers.isEmpty()) {
            int result = JOptionPane.showConfirmDialog(
                    this,
                    "Attention : Ce médecin a " + customers.size() + " patient(s) associé(s).\n" +
                            "Si vous le supprimez, ces patients n'auront plus de médecin référent.\n" +
                            "Voulez-vous vraiment continuer ?",
                    "Confirmation de suppression",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );
            if (result != JOptionPane.YES_OPTION) {
                return;
            }
        }
        int result = JOptionPane.showConfirmDialog(
                this,
                "Voulez-vous vraiment supprimer le médecin \"" + selectedDoctor.getFullName() + "\" ?",
                "Confirmation de suppression",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (result == JOptionPane.YES_OPTION) {
            for (Customer c : customers) {
                try {
                    c.setDoctorByLicenseNumber(null);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Le patient " + c.getFullName() + " n'a plus de médecin réferent", "Patients abandonné", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        DoctorList.removeDoctor(selectedDoctor);
        refreshTable();
        updateButtonsState();
        JOptionPane.showMessageDialog(this,
                "Médecin supprimé avec succès!",
                "Suppression réussie",
                JOptionPane.INFORMATION_MESSAGE);


    }

    private void refreshTable() {
        doctorsDisplayList.configTable(DoctorList.getDoctors(), HEADER_DOCTORS, USER_COLUMN_CLASSES);
    }


}


