package fr.sparadrap.ecf.view.swingview.doctor;

import fr.sparadrap.ecf.model.lists.person.CustomersList;
import fr.sparadrap.ecf.model.person.Doctor;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DoctorDetailsDialog extends JDialog {
    private Doctor doctor;

    private JPanel contentPane;
    private JPanel titlePanel;
    private JLabel titleLabel;
    private JTextArea detailsArea;
    private JPanel buttonPanel;
    private JButton closeBtn;

    public DoctorDetailsDialog(Frame frame, Doctor doctor) {
        super(frame, "Details du medecin", true);
        this.doctor = doctor;
        setContentPane(contentPane);
        setModal(true);

        setupDialog();
        initializeComponents();

        closeBtn.addActionListener(e -> this.dispose());
    }

    private void setupDialog() {
        this.setSize(500, 400);
        this.setLocationRelativeTo(getParent());
        this.setResizable(false);
    }

    private void initializeComponents() {
        long customersCount = CustomersList.getCustomers()
                .stream()
                .filter(customer -> customer.getDoctor().equals(doctor))
                .count();

        titleLabel.setText(doctor.getFullName());

        StringBuilder details = new StringBuilder();
        details.append("INFORMATIONS PERSONNELLES\n");
        details.append("═══════════════════════════\n\n");
        details.append("Nom complet: ").append(doctor.getFullName()).append("\n");
        details.append("Numéro d'agrément: ").append(doctor.getRpps()).append("\n\n");

        details.append("COORDONNÉES\n");
        details.append("═══════════════════════════\n\n");
        details.append("Adresse: ").append(doctor.getAddress()).append("\n");
        details.append("Code postal: ").append(doctor.getPostCode()).append("\n");
        details.append("Ville: ").append(doctor.getCity()).append("\n");
        details.append("Téléphone: ").append(doctor.getPhone()).append("\n");
        details.append("Email: ").append(doctor.getEmail()).append("\n\n");
        details.append("PATIENTS\n");
        details.append("═══════════════════════════\n\n");
        details.append("Nombre de patients: ").append(customersCount).append("\n");

        detailsArea.setText(details.toString());


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        titlePanel = new JPanel();
        titlePanel.setLayout(new BorderLayout(0, 0));
        contentPane.add(titlePanel, BorderLayout.NORTH);
        titleLabel = new JLabel();
        titleLabel.setText("Label");
        titlePanel.add(titleLabel, BorderLayout.NORTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        detailsArea = new JTextArea();
        detailsArea.setEditable(false);
        scrollPane1.setViewportView(detailsArea);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        contentPane.add(buttonPanel, BorderLayout.SOUTH);
        closeBtn = new JButton();
        closeBtn.setText("Fermer");
        buttonPanel.add(closeBtn);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
